"""Port: campaign persistence (campaigns, campaign_creators, campaign_requests)."""
from __future__ import annotations

from app.core.domain.campaign import Campaign, CampaignCreator, CampaignRequest


class CampaignStorePort:
    # ----------------------------------------------------------------- campaigns
    def create_campaign(self, campaign: Campaign) -> Campaign: ...
    def update_campaign(self, campaign: Campaign) -> Campaign: ...
    def get_campaign(self, campaign_id: str) -> Campaign | None: ...
    def list_campaigns(self) -> list[Campaign]: ...
    def delete_campaign(self, campaign_id: str) -> bool: ...
    def campaign_stats(self) -> dict: ...

    # ------------------------------------------------------- campaign creators
    def replace_creators(self, campaign_id: str, rows: list[CampaignCreator]) -> None: ...
    def list_creators(self, campaign_id: str) -> list[CampaignCreator]: ...
    def add_creator(self, row: CampaignCreator) -> CampaignCreator: ...
    def remove_creator(self, campaign_id: str, username: str) -> bool: ...
    def set_creator_status(self, campaign_id: str, username: str, status: str) -> bool: ...

    # ------------------------------------------------------ campaign requests
    def list_requests(self, campaign_id: str) -> list[CampaignRequest]: ...
    def add_request(self, request: CampaignRequest) -> CampaignRequest: ...
    def set_request_status(self, campaign_id: str, username: str, status: str) -> bool: ...